; PlatformIO Project Configuration File

[env:stm32f401cc]
platform = ststm32
framework = arduino
board = genericSTM32F401CC
board_build.mcu = stm32f401ccu6
board_build.f_cpu = 84000000L
monitor_speed = 115200
monitor_port = /dev/ttyACM0
upload_protocol = stlink
lib_deps =
  greiman/SdFat @ ^2.2.3
build_flags = -DDEBUG
  -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
  -D USBCON
  -D USBD_USE_CDC
